version: '3.8'

services:
  # Service Frontend (Blazor WebAssembly via Nginx)
  frontend:
    build:
      context: ../src
      dockerfile: ../docker/Dockerfile.App
    container_name: gameontonight-frontend
    ports:
      - "3000:80"
    volumes:
      - ../docker/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - gameontonight-network
    depends_on:
      - api
  
  # Service Backend API (.NET Web API)
  api:
    build:
      context: ../src
      dockerfile: ../docker/Dockerfile.Api
    container_name: gameontonight-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - JwtSettings__ExpiryMinutes=${JWT_EXPIRY_MINUTES:-60}
    networks:
      - gameontonight-network

networks:
  gameontonight-network:
    driver: bridge
