version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: gameontonight-postgres
    environment:
      - POSTGRES_USER=gameadmin
      - POSTGRES_PASSWORD=gamepassword
      - POSTGRES_DB=gameontonight
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - gameontonight-network

volumes:
  postgres_data:
    name: gameontonight-postgres-data

networks:
  gameontonight-network:
    name: gameontonight-network
