name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and test (.NET 9)
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      SOLUTION_PATH: src/GameOnTonight.sln
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK 9.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: |
            src/**/packages.lock.json
            src/**/*.csproj

      - name: Restore
        run: dotnet restore $SOLUTION_PATH

      - name: Build (Release)
        run: dotnet build $SOLUTION_PATH --configuration Release --no-restore

      - name: Test
        run: dotnet test $SOLUTION_PATH --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/TestResults/*.trx'
          if-no-files-found: ignore
